### PR TITLE
Prepare repo for use in 4.6

### PR DESCRIPTION
**Pull request by marun**
- Includes fixed renaming from #1 
- Switched to klog v2
- Bumped to kube 1.19.0-rc.2
- Renamed operator/* to pkg/*, in keeping with golang standards.

At some point dependent operators should switch off of this codebase, but this PR will at least allow it to be serviceable for 4.6.

### CODE REVIEW

**Comment by stlaz** [comment]
/lgtm
not sure the openshift/ -> pkg/ rename is kosher in case anyone's importing this, but I guess it's for the greater good

**Comment by marun** [comment]
> /lgtm
> not sure the openshift/ -> pkg/ rename is kosher in case anyone's importing this, but I guess it's for the greater good

Nobody is using this repo in the absence of Ben's commit to fixup the go module configuration, and I figured the import path for anyone switching will be changing anyway.

**Comment by sttts** [comment]
Where is it still used?

**Comment by marun** [comment]
> Where is it still used?

service-ca and console

**Pull request merged**
